### ISSUE TITLE
Bronchiole hierarchy needs to be revised

### ISSUE THREAD

**Issue by hrshdhgd** [hrshdhgd/uberon#21]
**Suggested revision and reasons**
Researching to fix issue #2952, I realised that there are some problems in the bronchiole hierarchy:
<img width="360" alt="image" src="https://github.com/obophenotype/uberon/assets/94959119/aac098a0-b1ef-4f0a-8ed5-b69a439c0ab0">
- [ ] bronchiole is 'part of' some 'pulmonary lobule'. This is not true, as not all bronchioles are part of a 'pulmonary lobule'. #2957
- [ ] 'pulmonary acinus' should be 'part of' some 'secondary pulmonary lobule'. #2957
- [ ] #2956
The text definition of 'pulmonary lobule' defines a 'secondary pulmonary lobule'. The text definition should define also pulmonary acinus, otherwise it is an exact synonym of 'secondary pulmonary lobule', and not a parent term of 'pulmonary acinus'. If a definition can not be found, this term maybe should be merged. According to this [reference](https://doi.org/10.53347/rID-8761), "For all intents and purposes, the terms "secondary pulmonary lobule", "primary pulmonary lobule", and "pulmonary lobule" are used synonymously".
- [ ] 'pulmonary lobule' 'has part' some 'terminal bronchiole'. This is not true, as 'pulmonary acinus' does not contain 'terminal bronchioles. This can be solved removing this axiom and with ticket #2952. #2957
- [ ] Add new axioms: 'terminal bronchiole' is ' distally connected to' some 'pulmonary acinus', and 'pulmonary acinus' is 'connected to' some 'terminal bronchiole'. #2957
- [ ] Edit 'pulmonary acinus'
